dataset_dir: output/features/davis/
learning_rate: !!float 0.001
total_iterations: 1500
eval_freq: 20
residual_layers: [8, 16, 32, 64]
contrastive_weight: 1.
prior_weight: 0.1
skip_weight: 0.1
#pretrained_model: amber-shadow-351.pt

wandb:
  project: 'diffusion-tracker'
  entity: 'maxis-organization'